baseURL = 'http://muja.dev/'
languageCode = 'en-us'
title = 'Muja Siyam'
theme = 'coder'
# site info
defaultContentLanguage = 'en'
paginate = 20
pygmentsStyle = "bw"
pygmentsCodeFences = true
pygmentsCodeFencesGuessSyntax = true
enableEmoji = true
# Enable Disqus comments
disqusShortname = "mujasiyam"

[params]
author = 'Muja Siyam'
description = 'Muja Siyam personal website,portfolio'
keywords = 'blog,developer,personal'
info = ['Full Stack DevSecOps', 'Magician']
avatarURL = 'images/avatar.jpg'
gravatar = "contact@muja.dev"
dateFormat = "January 2, 2006"
since = 2012
# Git Commit in Footer, uncomment the line below to enable it
commit = "https://api.github.com/repos/xmawja/muja.dev/git/refs/heads/main"
# Right To Left, language support
rtl = true
# Specify light/dark colorscheme
# Supported values:
# "auto" (use preference set by browser)
# "dark" (dark background, light foreground)
# "light" (light background, dark foreground) (default)
colorScheme = 'auto'
# Hide the toggle button, along with the associated vertical divider
hideColorSchemeToggle = false
# Series see also post count
maxSeeAlsoItems = 5
# Custom CSS
customCSS = []
# Custom SCSS, file path is relative to Hugo's asset folder (default: {your project root}/assets)
customSCSS = []
# Custom JS
customJS = []

# If you want to use fathom(https://usefathom.com) for analytics, add this section
# [params.fathomAnalytics]
# siteID = "ABCDE"
# serverURL = "analytics.example.com" # Default value is cdn.usefathom.com, overwrite this if you are self-hosting

# If you want to use plausible(https://plausible.io) for analytics, add this section
# [params.plausibleAnalytics]
# domain = "example.com"
# serverURL = "analytics.example.com" # Default value is plausible.io, overwrite this if you are self-hosting or using a custom domain

# If you want to use goatcounter(https://goatcounter.com) for analytics, add this section
# [params.goatCounter]
# code = "code"

# If you want to use Cloudflare Web Analytics(https://cloudflare.com) for analytics, add this section
# [params.cloudflare]
# token = "token"

# If you want to use Matomo(https://matomo.org) for analytics, add this section
# [params.matomo]
# siteID = "ABCDE" # Default value is "1", overwrite this if you are cloud-hosting
# serverURL = "analytics.example.com" # For cloud-hosting, use provided URL, e.g. example.matomo.cloud

# If you want to use Google Tag Manager(https://analytics.google.com/) for analytics, add this section
# [params.googleTagManager]
# id = "gid"

# If you want to use Application Insights(https://azure.com/) for analytics, add this section
# [params.applicationInsights]
# connectionString = "connectionString"

# If you want to implement a Content-Security-Policy, add this section
# [params.csp]
# childsrc = ["'self'"]
# fontsrc = ["'self'", "https://fonts.gstatic.com", "https://cdn.jsdelivr.net/"]
# formaction = ["'self'"]
# framesrc = ["'self'", "https://www.youtube.com"]
# imgsrc = ["'self'"]
# objectsrc = ["'none'"]
# stylesrc = [
#   "'self'",
#   "'unsafe-inline'",
#   "https://fonts.googleapis.com/",
#   "https://cdn.jsdelivr.net/",
# ]
# scriptsrc = [
#   "'self'",
#   "'unsafe-inline'",
#   "https://www.google-analytics.com",
#   "https://cdn.jsdelivr.net/",
# ]
# prefetchsrc = ["'self'"]
# # connect-src directive – defines valid targets for to XMLHttpRequest (AJAX), WebSockets or EventSource
# connectsrc = ["'self'", "https://www.google-analytics.com"]

[taxonomies]
category = "categories"
series = "series"
tag = "tags"
author = "authors"

[[params.social]]
name = "Github"
icon = "fa fa-2x fa-github"
weight = 1
url = "https://github.com/xmawja/"

[[params.social]]
name = "Gitlab"
icon = "fa fa-2x fa-gitlab"
weight = 2
url = "https://gitlab.com/xmawja/"

[[params.social]]
name = "Twitter"
icon = "fa fa-2x fa-twitter"
weight = 3
url = "https://twitter.com/xmawja/"

[[params.social]]
name = "LinkedIn"
icon = "fa fa-2x fa-linkedin"
weight = 4
url = "https://www.linkedin.com/in/mujasiyam/"

[[params.social]]
name = "Medium"
icon = "fa fa-2x fa-medium"
weight = 5
url = "https://medium.com/@mujasiyam"

[[params.social]]
name = "RSS"
icon = "fa fa-2x fa-rss"
weight = 6
url = "https://muja.dev/index.xml"
rel = "alternate"
type = "application/rss+xml"

# english content page
[languages.en]
languageName = ":us:"

[[languages.en.menu.main]]
name = "About"
weight = 1
url = "about/"

[[languages.en.menu.main]]
name = "Blog"
weight = 2
url = "posts/"

[[languages.en.menu.main]]
name = "Projects"
weight = 3
url = "projects/"

[[languages.en.menu.main]]
name = "Contact me"
weight = 5
url = "contact/"

# french content pages
[languages.fr-fr]
languageName = ":fr:"
title = "Muja Siyam"

[languages.fr-fr.params]
author = "Muja Siyam"
info = ['Full Stack DevSecOps', 'Magicien']
description = "site personnel Muja Siyam"
keywords = "blog,développeur,personnel,portefeuille"

[[languages.fr-fr.menu.main]]
name = "Propos"
weight = 1
url = "about/"

[[languages.fr-fr.menu.main]]
name = "Blog"
weight = 2
url = "posts/"

[[languages.fr-fr.menu.main]]
name = "Projet"
weight = 3
url = "projects/"

[[languages.fr-fr.menu.main]]
name = "Contact"
weight = 5
url = "contact/"

# arabic content pages
[languages.ar-sa]
languageName = ":sa:"
title = "موجا صيام"

[languages.ar-sa.params]
author = "موجا صيام"
info = ['مهندس برمجيات - متخصص DevSecOps', 'ساحر']
description = "الموقع الشخصي ل موجا صيام"
keywords = "مدونة,مطور,شخصي,بوابة"

[[languages.ar-sa.menu.main]]
name = "عني"
weight = 1
url = "about/"

[[languages.ar-sa.menu.main]]
name = "المدونة"
weight = 2
url = "posts/"

[[languages.ar-sa.menu.main]]
name = "مشاريع"
weight = 3
url = "projects/"

[[languages.ar-sa.menu.main]]
name = "اتصل بي"
weight = 5
url = "contact/"
